version: "3"
services:
  rabbitmq:
    image: rabbitmq:3.12-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
    ports:
      - 5672:5672
      - 15672:15672

  thumbnail:
    depends_on:
      - rabbitmq
    restart: always
    build:
      context: ./thumbnail

    env_file:
      - .env
    
    ports:
      - 5400:5400
      - 5555:5555

  
  votes:
    depends_on:
      - rabbitmq
    restart: always
    build:
      context: ./votes

    env_file:
      - .env
    
    ports:
      - 5000:5000
